version: "3.8"
services:
  # api:
  #   image: turbo-todo-api:${RELEASE_VERSION}
  #   build:
  #     context: .
  #     dockerfile: deploy/docker/Dockerfile
  #     target: api
  #   ports:
  #     - "5000:5000"

  # events-listener:
  #   image: turbo-todo-events-listener:${RELEASE_VERSION}
  #   build:
  #     context: .
  #     dockerfile: deploy/docker/Dockerfile
  #     target: eventslistener
  #   ports:
  #     - "5001:5001"

  nats:
    image: nats:2.7.4-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  cockroachdb:
    image: cockroachdb/cockroach:v21.2.7
    ports:
      - "26257:26257"
      - "8080:8080"
    command: "start-single-node --advertise-addr 'localhost' --insecure"
