server:
  host: "localhost"
  port: 5000

messaging:
  host: "localhost"
  port: 4222

database:
  host: "localhost:26257"
  user: "admin"
  pass: "password"
  db_name: "turbotodo"
  skip_schema: false